<?php
/*
These sample pages are provided for information purposes only. It does not imply any recommendation or endorsement by anyone.
  These sample pages are provided for FREE.
  There is no warranty and no additional document. USE AT YOUR OWN RISK.
*/
//SAMPLE MERCHANT PAYMENT PAGE - using PHP cURL and JSON




//Merchant will need to edit the below parameter to match their environment.


		$apiid = 'XXXXX';											//Get your API ID on iBill.my
		$apisecret = 'XXXXXXXXXX';									//Get your API secret key on iBill.my
		$apiname = 'Ahmad Bin Mutalib';								//Your customer name					Value Attribute: varchar(255)
		$apiemail = 'ahmadmutailb@gmail.com';						//Your customer email					Value Attribute: varchar(255)
		$apiphone = '60123456789';									//Your customer phone no.				Value Attribute: varchar(255)
		$apiaddress = 'No. 23 Jalan Damai 76342 Kuala Lumpur';		//Your customer address					Value Attribute: varchar(255)
		$apiamount = '421.90';										//Total customer need to pay			Value Attribute: decimal(18,2)
		$apidetails = 'Payment for invoice 2031';					//Payment detail						Value Attribute: varchar(255)
		$apiorderid = '2031';										//Order ID generated by your system		Value Attribute: varchar(255)

		//Generate your hashcode
		$apihashcode = md5($apisecret.$apiid.$apiorderid.$apiamount);
		
		//Create an array
		$postJSON = array(
			'apiid'=>$apiid,
			'apihashcode'=>$apihashcode,
			'apiname'=>$apiname,
			'apiemail'=>$apiemail,
			'apiphone'=>$apiphone,
			'apiaddress'=>$apiaddress,
			'apiamount'=>$apiamount,
			'apidetails'=>$apidetails,
			'apiorderid'=>$apiorderid);
			
		//Convert To JSON
		$post = json_encode($postJSON);
		

		//General cURL headers
		function get_furl($url)
		{
			$furl = false;

			// First check response headers
			$headers = get_headers($url);

			// Test for 301 or 302
			if(preg_match('/^HTTP\/\d\.\d\s+(301|302)/',$headers[0]))
			{
				foreach($headers as $value)
				{
					if(substr(strtolower($value), 0, 9) == "location:")
					{
						$furl = trim(substr($value, 9, strlen($value)));
					}
				}
			}
			// Set final URL
			$furl = ($furl) ? $furl : $url;

			return $furl;
		}
		
		//Sample cURL
		$url = get_furl('https://ibill.my/merchant/?ng=client/iview/standard_api/');		//link need to send data
		$ch = curl_init($url);
		curl_setopt($ch, CURLOPT_HEADER, 0);
		curl_setopt($ch, CURLOPT_POSTFIELDS, $post);
		curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
		curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
		curl_setopt($ch, CURLOPT_TIMEOUT, 2);
		$contents = curl_exec($ch);
		curl_close($ch);
		echo $contents;


?>
